### ISSUE TITLE
Problem with adetailer, look at face and hands

### ISSUE THREAD

**Issue by Malapris** [hako-mikan/sd-webui-cd-tuner#21]
![00024-monmixturbo8 0 8(monmixturbo7 0 5(SDXL_TURBO_240108_socababesTurboXL_v12Hybrid) + 0 5(SDXL_Réaliste_ENTEST_240111_realisticStock s2158647632 cfg2 75 DPM++ SDE ](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/123722969/b34ff5f2-274f-4f95-8695-c0a1c10f81a4)

**Comment by Malapris** [comment]
this is very anoying, what kind of settings should I use ?
![image](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/123722969/7b85f287-c975-423f-95a1-8458eec9f82e)

**Comment by wogam** [comment]
I'm getting the same issue - CDT is not working during Adetailer inpainting. I have even tried using `<cdt:0;0;0;0;-10>` in the prompt for adetailer and it still doesn't work.

**Comment by miasik** [comment]
The same here. Both adetailer and uddetailer produces the same visible squares for faces either with and without its control string in the prompt.

![319336192-36-DPM++ 3M SDE Karras-225044_363051](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/1073832/a468b0c5-5a0c-493a-a1b4-b2908c95ca27)

**Comment by Malapris** [comment]
please allow CDtuner to run AFTER all renderings

**Comment by hako-mikan** [comment]
Added option "Apply once".
Checking this option, you can prevent applying CD tuner in Adetailer.
The CD Tuner is an extension that acts during generation, so it's not practical to apply it after generation. From my testing, it seems there are no issues even if I stop applying it before Adetailer starts. This is likely because Adetailer processes through i2i.
